<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-JEI8AS0O" failures="1" tests="4" name="PIM Test" time="33.275" errors="0" timestamp="2022-11-20T16:30:45 GMT-05:00">
  <testcase classname="testcases.LoginTest" name="loginSuccess_001" time="6.68"/>
  <testcase classname="testcases.PIMTest" name="getRecordCountItem_009" time="3.119">
    <failure type="java.lang.AssertionError" message="expected [41] but found [43]">
      <![CDATA[java.lang.AssertionError: expected [41] but found [43]
at testcases.PIMTest.getRecordCountItem_009(PIMTest.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- getRecordCountItem_009 -->
  <testcase classname="testcases.PIMTest" name="getRecordItem_010" time="3.45"/>
  <testcase classname="testcases.LoginTest" name="LoginUnsuccessful_002" time="16.826"/>
</testsuite> <!-- PIM Test -->
