<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JEI8AS0O" ignored="0" name="PIM Test" tests="4" failures="1" timestamp="2022-11-20T16:43:32 EST" time="35.903" errors="0">
  <testcase name="loginSuccess_001" time="4.826" classname="testcases.LoginTest"/>
  <testcase name="getRecordCountItem_009" time="3.454" classname="testcases.PIMTest">
    <failure type="java.lang.AssertionError" message="expected [41] but found [43]">
      <![CDATA[java.lang.AssertionError: expected [41] but found [43]
at testcases.PIMTest.getRecordCountItem_009(PIMTest.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- getRecordCountItem_009 -->
  <testcase name="getRecordItem_010" time="5.291" classname="testcases.PIMTest"/>
  <testcase name="LoginUnsuccessful_002" time="17.896" classname="testcases.LoginTest"/>
</testsuite> <!-- PIM Test -->
